name: 'Create dependency graph'
description: 'Returns order of install for Terraform stacks using dependencies.json'
outputs:
  json_directory_list:
    description: "List of the stacks to deploy in dependency order in JSON format"
    value: ${{ steps.stack_order.outputs.order }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Find order of stacks
      shell: bash
      id: stack_order
      run: echo "order=$(python ${{ github.action_path }}/main.py)" >> $GITHUB_OUTPUT