name: Run 

on:
    workflow_call:
      inputs:
        terraform_version:
          required: false
          default: "1.5.2"
          type: string
        environment_name:
          required: false
          default: "development"
          type: string              
        aws_account:
          required: false
          default: "1234567890"
          type: string
          description: "The number of the AWS account where the resources will be applied"
        aws_region:
          required: false
          default: "eu-west-2"
          type: string
      secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true

jobs:
  define_matrix:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.directories.outputs.json_directory_list }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate list of directories
        id: directories
        run: |
          directories=""

          core_services_subdirs=$(find ./core-services -maxdepth 1 -type d | sort -V)
          application_subdirs=$(find ./applications -maxdepth 1 -type d | sort -V)
          all_subdirs=$(printf "%s\n%s\n" "$core_services_subdirs" "$application_subdirs")
          for dir in $all_subdirs; do
            # Check if the subdirectory contains a main.tf file
            if [ -f "$dir/main.tf" ]; then
              directories+="$dir,"
            else
              echo "No Terraform configuration found in $dir, skipping..."
            fi
          done

          json_directory_list=$(echo -n "${directories%,}" | jq -Rs 'split(",") | map(select(. != ""))' | tr '\n' ' ')
          echo $json_directory_list
          echo "json_directory_list=$json_directory_list" >> "$GITHUB_OUTPUT"
    
  build:
    name: Build AWS Infrastructure - ${{ matrix.directory }}
    runs-on: ubuntu-latest
    needs:
      - define_matrix
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.define_matrix.outputs.directories) }}
      max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ matrix.directory }}
            environment
            globals.tf

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Copy files
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: |
          cp versions.tf "$DIRECTORY"/

      - name: Find Terraform variables
        id: variables
        env:
          DIRECTORY: ${{ matrix.directory }}
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        run: |
          find_app_var_files() {
            local dir=$1
            local state_name=$(basename "$dir")
            local tfvars="$dir/tfvars/${state_name}-${ENVIRONMENT_NAME}.tfvars"
            local json="$dir/tfvars/${state_name}-${ENVIRONMENT_NAME}.tfvars.json"
            if [[ -f "$tfvars" ]]; then
              echo "-var-file=$tfvars"
            elif [[ -f "$json" ]]; then
              echo "-var-file=$json"
            fi
          }

          find_env_var_files() {
            local tfvars="environment/${ENVIRONMENT_NAME}.tfvars"
            local tfvars="environment/${ENVIRONMENT_NAME}.tfvars.json"
            if [[ -f "$tfvars" ]]; then
              echo "-var-file=$tfvars"
            elif [[ -f "$json" ]]; then
              echo "-var-file=$json"
            fi
          }

          global_vars_file="-var-file=$(readlink -f globals.tfvars)"
          app_var_file=$(find_app_var_files "$DIRECTORY") 
          env_var_file=$(find_env_var_files)
          full_variable_flags="$global_vars_file $app_var_file $env_var_file"

          echo "tf_vars=$full_variable_flags" >> $GITHUB_OUTPUT

      - name: Terraform Init
        working-directory: ${{ matrix.directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}
          AWS_ACCOUNT_NUMBER: ${{ inputs.aws_account }}
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
          DIRECTORY: ${{ matrix.directory }}
        run: |
          state_name=$(basename "$DIRECTORY")
          terraform init \
            -backend-config=dynamodb_table="${AWS_REGION}"-state-locks \
            -backend-config=bucket="${AWS_ACCOUNT_NUMBER}"-"${AWS_REGION}"-state \
            -backend-config=key="${ENVIRONMENT_NAME}"/"$state_name"/terraform.tfstate
        
      - name: Terraform Plan
        working-directory: ${{ matrix.directory }}
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
          TERRAFORM_VARIABLES: ${{ steps.variables.outputs.tf_vars }}
        run: terraform plan -no-color -input=false -out=tfplan ${TERRAFORM_VARIABLES}

      - name: Terraform Apply
        working-directory: ${{ matrix.directory }}
        env: 
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
          TERRAFORM_VARIABLES: ${{ steps.variables.outputs.tf_vars }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}
        run: echo terraform apply -no-color -input=false tfplan

  