name: Build Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: 'eu-west-1'
        run: |
          # TODO: Construct the DynamoDB table and the bucket name
          run_terraform() {
            dir=$1
            state_name=$(basename $dir)
            cp versions.tf "$dir/"
            pushd $dir
            terraform init \
              -backend-config=dynamodb_table=${AWS_REGION}-state-locks \
              -backend-config=bucket=891377327213-${AWS_REGION}-state \
              -backend-config=key=development/$state_name/terraform.tfstate
            terraform plan -no-color -input=false -out=tfplan
            terraform apply -no-color -input=false tfplan
            popd
          }
          core_services_subdirs=$(find ./core-services -maxdepth 1 -type d | sort -V)
          application_subdirs=$(find ./applications -maxdepth 1 -type d | sort -V)
          all_subdirs=$(printf "%s\n%s\n" "$core_services_subdirs" "$application_subdirs")
          for dir in $all_subdirs ; do
              if [ -f "$dir/main.tf" ]; then
                run_terraform "$dir"
              else
                  echo "No Terraform configuration found in $dir, skipping..."
              fi
          done