name: Destroy Infrastructure

on: 
  workflow_dispatch:
  schedule:
    - cron: "30 05 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: 'eu-west-1'
        run: |
          run_terraform() {
            dir=$1
            state_name=$(basename $dir)
            cp versions.tf "$dir/"
            pushd $dir
            app_var_file=$(find_app_var_files "$dir")
            env_var_file=$(find_env_var_files)
            terraform init \
              -backend-config=dynamodb_table=${AWS_REGION}-state-locks \
              -backend-config=bucket=891377327213-${AWS_REGION}-state \
              -backend-config=key=production/$state_name/terraform.tfstate
            terraform destroy -no-color -auto-approve -input=false -var-file="$global_vars_file" $app_var_file $env_var_file
            popd
          }

          find_app_var_files() {
            local dir=$1
            local dir_name=$(basename "$dir")
            local tfvars="$dir/tfvars/${dir_name}-production.tfvars"
            local json="$dir/tfvars/${dir_name}-production.tfvars.json"
            if [[ -f "$tfvars" ]]; then
              echo "-var-file=$tfvars"
            elif [[ -f "$json" ]]; then
              echo "-var-file=$json"
            fi
          }

          find_env_var_files() {
            local tfvars="../../environment/production.tfvars"
            local tfvars="../../environment/production.tfvars.json"
            if [[ -f "$tfvars" ]]; then
              echo "-var-file=$tfvars"
            elif [[ -f "$json" ]]; then
              echo "-var-file=$json"
            fi
          }

          core_services_subdirs=$(find ./core-services -maxdepth 1 -type d | sort -V --reverse)
          application_subdirs=$(find ./applications -maxdepth 1 -type d | sort -V --reverse)
          all_subdirs=$(printf "%s\n%s\n" "$application_subdirs" "$core_services_subdirs")
          global_vars_file=$(readlink -f globals.tfvars)
          for dir in $all_subdirs ; do
              if [ -f "$dir/main.tf" ]; then
                run_terraform "$dir"
              else
                  echo "No Terraform configuration found in $dir, skipping..."
              fi
          done