on:
    push:
        branches:
            - main

jobs:
  call:
    uses: ./.github/workflows/_terraform.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
